"""Smart unique task lexicon for AgentGo SA4 case-study 6000 — v2 pure · unique · smart."""
from __future__ import annotations

THEME_CTX: dict[str, dict] = {
    "t01-case-copy": {
        "short": "Narrative",
        "object": "case study prose (challenge · shipped · verification)",
        "path": "SourceA-landing/green-unified/case-studies/agentgo.html",
        "metric": "buyer comprehension in one screen",
    },
    "t02-landing-ship": {
        "short": "Landing",
        "object": "sourcea.app case study route + gates",
        "path": "SourceA-landing/green-unified/case-studies/agentgo.html",
        "metric": "commercial + depth gate PASS",
    },
    "t03-proof-receipts": {
        "short": "Proof",
        "object": "disk receipts · manifests · screenshots",
        "path": "~/.sina/agentgo-case-study-receipt-v1.json",
        "metric": "PASS/FAIL not vibes",
    },
    "t04-sa4-source": {
        "short": "SA4 tree",
        "object": "SA4 static tree (~1259 HTML pages)",
        "path": "~/Desktop/SA4",
        "metric": "page inventory hash",
    },
    "t05-geo-trackers": {
        "short": "Trackers",
        "object": "AI visibility tracker landings (ChatGPT · Perplexity · Gemini · Claude · Grok · Qwen)",
        "path": "~/Desktop/SA4/chatgpt-visibility-tracker",
        "metric": "tracker index coverage",
    },
    "t06-research-hub": {
        "short": "Research",
        "object": "research + guides + glossary hub",
        "path": "~/Desktop/SA4/research",
        "metric": "research article count",
    },
    "t07-compare-pages": {
        "short": "Compare",
        "object": "GEO  compare matrix (Peec · Profound · Otterly adjacency)",
        "path": "~/Desktop/SA4/compare",
        "metric": "compare URL completeness",
    },
    "t08-dual-deploy": {
        "short": "Dual deploy",
        "object": "Agent Run :5180 + SA4 AgentGo :8080 parity",
        "path": "scripts/deploy_sourcea_desktop_landing_v1.py",
        "metric": "validate-sourcea-desktop-landing PASS",
    },
    "t09-wil-gate": {
        "short": "Wil gate",
        "object": "Wil L3 separation law + ship gate receipts",
        "path": "~/Desktop/YA5/.cursor/governance/TERMINOLOGY_2026.md",
        "metric": "AgentGo ≠ SourceA disclaimer present",
    },
    "t10-revenue-crm": {
        "short": "Revenue",
        "object": "SaaS/marketing ICP CRM + outreach",
        "path": "scripts/sourcea_revenue_engine_crm_v1.py",
        "metric": "outreach_sent logged",
    },
}

ANGLE_CTX: dict[str, dict] = {
    "cs-a-factory": {
        "short": "Factory",
        "buyer": "marketing leader who needs category surface at factory speed",
        "pure_law": "Pure story: controlled pipeline → 1259-page GEO surface. Not a PureFlow trades clone.",
        "verify": "test -d ~/Desktop/SA4 && find ~/Desktop/SA4 -name '*.html' 2>/dev/null | wc -l",
        "anti": "Never claim live SaaS billing — SA4 is marketing surface proof.",
    },
    "cs-b-dual": {
        "short": "Dual",
        "buyer": "agency CTO who wants screen-share deploy proof on desktop",
        "pure_law": "Pure story: one green-unified spine · two desktop shells (cinematic + canonical).",
        "verify": "bash ~/Desktop/SourceA/scripts/validate-sourcea-desktop-landing-v1.sh",
        "anti": "Never conflate localhost demo with production sourcea.app ship.",
    },
    "cs-c-wil": {
        "short": "Wil",
        "buyer": "portfolio strategist evaluating L3 Wil mirror vs SourceA governance",
        "pure_law": "Pure story: Wil AI ecosystem intelligence hosts SourceA lane — products stay separate.",
        "verify": "test -f ~/Desktop/YA5/.cursor/governance/TERMINOLOGY_2026.md",
        "anti": "Never sell AgentGo sign-in localhost:3001 as production.",
    },
}

WS_PROGRESS: dict[str, list[dict]] = {
    "w01-ship": [
        {"title": "Micro-ship", "verb": "Ship smallest buyer-visible slice of", "detail": "One shippable artifact only — no drive-by refactors.", "receipt": "file logged"},
        {"title": "Route wire", "verb": "Wire nav + breadcrumb for", "detail": "Link from offer + footer; PureFlow stays case #1.", "receipt": "grep link in offer.html"},
        {"title": "Gate add", "verb": "Add page to commercial + depth gates for", "detail": "Update landing-commercial-copy-audience + copy-depth JSON.", "receipt": "validate-landing-commercial-copy PASS"},
        {"title": "OG polish", "verb": "Polish OG title + meta for", "detail": "One sharp sentence — no ALLOW/BLOCK repetition.", "receipt": "depth gate PASS"},
        {"title": "CTA align", "verb": "Align CTA to Revenue Engine for", "detail": "cal.com/sourcea/proof-demo + hello@sourcea.app only.", "receipt": "CTA grep PASS"},
        {"title": "Subset pick", "verb": "Pick 10-page public demo subset from", "detail": "Home + 3 trackers + 3 compare + 3 research — honest scope.", "receipt": "manifest JSON"},
        {"title": "Sync mirror", "verb": "Sync sites/ mirror if required for", "detail": "SourceA-landing canonical first.", "receipt": "diff policy ok"},
        {"title": "Deploy recipe", "verb": "Run run-recipe deploy step for", "detail": "agentrun-app + SA4 when ship window open.", "receipt": "deploy script exit 0"},
        {"title": "Screenshot", "verb": "Capture proof screenshot for", "detail": "Store under ~/.sina/ — not chat memory.", "receipt": "png path"},
        {"title": "Index card", "verb": "Add index row for", "detail": "AGENTGO-CASE-STUDY-6000 machine index.", "receipt": "markdown row"},
        {"title": "Offer cross", "verb": "Cross-link offer.html to", "detail": "Two case studies: PureFlow local · AgentGo scale.", "receipt": "link present"},
        {"title": "Footer wire", "verb": "Wire footer case study column for", "detail": "Both pureflow + agentgo links.", "receipt": "footer grep"},
        {"title": "Cal event", "verb": "Add Cal.com talking point for", "detail": "Screen-share script bullet.", "receipt": "CRM note"},
        {"title": "LinkedIn hook", "verb": "Draft one LinkedIn proof line for", "detail": "Founder voice — not generic AI hype.", "receipt": "draft md"},
        {"title": "Video beat", "verb": "Map commercial film beat for", "detail": "Separation disclaimer on screen if filmed.", "receipt": "beat json row"},
        {"title": "Hub glance", "verb": "Optional Hub official link for", "detail": "Founder session light only.", "receipt": "hub config"},
        {"title": "Subdomain plan", "verb": "Document subdomain option for", "detail": "agentgo.sourcea.app — defer until ASF.", "receipt": "decision note"},
        {"title": "Rollback", "verb": "Document rollback for", "detail": "One-command revert path.", "receipt": "rollback md"},
        {"title": "Ship seal", "verb": "Seal ship receipt for", "detail": "landing_ship gate satisfied.", "receipt": "gate receipt json"},
        {"title": "Ship retro", "verb": "Write 5-line ship retro for", "detail": "What worked · what blocked · next slice.", "receipt": "retro md"},
    ],
    "w02-prove": [
        {"title": "Inventory", "verb": "Inventory disk truth for", "detail": "Count files — quote paths not chat.", "receipt": "wc output"},
        {"title": "Manifest", "verb": "Write manifest JSON for", "detail": "schema + generated_at + counts.", "receipt": "manifest file"},
        {"title": "Sitemap", "verb": "Parse sitemap.xml scope for", "detail": "SA4 sitemap line count vs claim.", "receipt": "sitemap stat"},
        {"title": "Tracker audit", "verb": "Audit tracker folder index.html for", "detail": "Each major LLM vendor represented.", "receipt": "audit list"},
        {"title": "Compare audit", "verb": "Audit compare/  pages for", "detail": "No false superiority claims.", "receipt": "audit md"},
        {"title": "Research sample", "verb": "Sample 5 research articles for", "detail": "Quality bar — not thin SEO spam.", "receipt": "sample urls"},
        {"title": "Proof pack", "verb": "Attach proof pack row for", "detail": "chat-unify-proof-pack if applicable.", "receipt": "proof json"},
        {"title": "Tamper demo", "verb": "Prep tamper-FAIL demo snippet for", "detail": "Procurement screen-share.", "receipt": "demo script"},
        {"title": "Boot wire", "verb": "Wire sourcea-boot eval path for", "detail": "Buyer 1 self-serve.", "receipt": "boot PASS"},
        {"title": "Metric block", "verb": "Add honest metrics block for", "detail": "1259 pages · June 2026 · localhost caveat.", "receipt": "html block"},
        {"title": "Diff PureFlow", "verb": "Document diff vs PureFlow for", "detail": "Local trades vs category GEO — table.", "receipt": "comparison md"},
        {"title": "Receipt gate", "verb": "Map receipt_gate column for", "detail": "REGISTRY.json alignment.", "receipt": "gate map"},
        {"title": "Validator", "verb": "Run validate-agentgo-case-study-6000 for", "detail": "Mac-safe counts + unique titles.", "receipt": "bash PASS"},
        {"title": "Unique titles", "verb": "Prove 2000 unique titles in angle pack for", "detail": "No duplicate title strings.", "receipt": "python assert"},
        {"title": "Phase audit", "verb": "Audit NOW rows 1–30 concrete for", "detail": "No generic slice filler.", "receipt": "spot check"},
        {"title": "Separation", "verb": "Prove AgentGo ≠ SourceA copy for", "detail": "Footer disclaimer grep.", "receipt": "grep PASS"},
        {"title": "Wil cite", "verb": "Cite Wil TERMINOLOGY lines for", "detail": "Read-only — no duplicate 11k counts.", "receipt": "citation block"},
        {"title": "Dual ports", "verb": "Prove :5180 and :8080 routes for", "detail": "curl local when servers up.", "receipt": "curl log"},
        {"title": "Seal proof", "verb": "Seal proof_pack_sealed row for", "detail": "Phase-1 ticket if applicable.", "receipt": "seal json"},
        {"title": "Prove retro", "verb": "Archive prove retro for", "detail": "knowledge-library path.", "receipt": "lesson md"},
    ],
    "w03-sell": [
        {"title": "ICP define", "verb": "Define ICP one-pager for", "detail": "SaaS marketing · GEO buyer — not pool owner.", "receipt": "icp md"},
        {"title": "CRM seed", "verb": "Seed CRM placeholder for", "detail": "sourcea_revenue_engine_crm_v1.py add.", "receipt": "crm json"},
        {"title": "Outreach A", "verb": "Draft outreach template A for", "detail": "Factory scale angle.", "receipt": "template md"},
        {"title": "Outreach B", "verb": "Draft outreach template B for", "detail": "Dual deploy angle.", "receipt": "template md"},
        {"title": "Outreach C", "verb": "Draft outreach template C for", "detail": "Wil portfolio angle.", "receipt": "template md"},
        {"title": "Subject line", "verb": "Write 3 subject lines for", "detail": "Proof-backed · no hype.", "receipt": "subjects txt"},
        {"title": "Objection", "verb": "Write objection handler for", "detail": "Is this live SaaS? → honest answer.", "receipt": "objection md"},
        {"title": "Pricing tie", "verb": "Tie to Asset B SKU for", "detail": "$3–10K loop build · not GEO subscription.", "receipt": "sku crosswalk"},
        {"title": "Cal script", "verb": "Write 15-min Cal script for", "detail": "Screen-share order.", "receipt": "script md"},
        {"title": "Case email", "verb": "Write case study email for", "detail": "Link pureflow + agentgo.", "receipt": "email md"},
        {"title": "Agency pitch", "verb": "Write agency variant for", "detail": "White-label factory narrative.", "receipt": "pitch md"},
        {"title": "Founder send", "verb": "Log founder-approved send for", "detail": "t1-pipeline-send-log.", "receipt": "send log"},
        {"title": "Touch CRM", "verb": "Advance CRM stage for", "detail": "outreach_sent minimum.", "receipt": "crm touch"},
        {"title": "W3 signal", "verb": "Log W3 economic signal for", "detail": "CAD ≥2K path.", "receipt": "metric row"},
        {"title": "NW parallel", "verb": "Note Noetfield parallel for", "detail": "Do not merge ICPs.", "receipt": "note"},
        {"title": "Retainer hook", "verb": "Add retainer upsell line for", "detail": "$2–5K/mo receipt export.", "receipt": "copy block"},
        {"title": "Proposal", "verb": "Draft 1-page proposal for", "detail": "Fixed scope · receipts.", "receipt": "proposal md"},
        {"title": "SOW", "verb": "Draft SOW skeleton for", "detail": "Bounded paths listed.", "receipt": "sow md"},
        {"title": "Win retro", "verb": "Log win/loss retro for", "detail": "Even loss gets receipt.", "receipt": "retro"},
        {"title": "Sell seal", "verb": "Seal revenue_outreach gate for", "detail": "CRM proof.", "receipt": "crm json"},
    ],
    "w04-build": [
        {"title": "Scaffold", "verb": "Scaffold build slice for", "detail": "Smallest code/html change.", "receipt": "git diff"},
        {"title": "HTML sect", "verb": "Build HTML section for", "detail": "green-unified components.", "receipt": "html file"},
        {"title": "CSS hook", "verb": "Add CSS hook for", "detail": "sourcea.css only if needed.", "receipt": "css diff"},
        {"title": "JS wire", "verb": "Wire JS behavior for", "detail": "motion · CTA gate.", "receipt": "js diff"},
        {"title": "Tracker page", "verb": "Extract one tracker page for", "detail": "From SA4 into demo subset.", "receipt": "html path"},
        {"title": "Compare page", "verb": "Extract one compare page for", "detail": " fair-use.", "receipt": "html path"},
        {"title": "Research card", "verb": "Build research card component for", "detail": "Case study embed.", "receipt": "component"},
        {"title": "Metric card", "verb": "Build metric card for", "detail": "1259 · trackers · research counts.", "receipt": "component"},
        {"title": "Angle tabs", "verb": "Build three-angle tab UI for", "detail": "A factory · B dual · C Wil.", "receipt": "ui block"},
        {"title": "Breadcrumb", "verb": "Build breadcrumb for", "detail": "Home / Offer / AgentGo.", "receipt": "nav"},
        {"title": "Schema", "verb": "Add JSON-LD schema for", "detail": "CaseStudy type.", "receipt": "head block"},
        {"title": "A11y", "verb": "Fix a11y for", "detail": "skip link · aria.", "receipt": "axe or manual"},
        {"title": "Mobile", "verb": "Harden mobile layout for", "detail": "responsive patterns.", "receipt": "viewport check"},
        {"title": "Perf", "verb": "Light perf pass for", "detail": "No hero video bloat.", "receipt": "lighthouse skim"},
        {"title": "Deploy script", "verb": "Patch deploy script for", "detail": "If dual-deploy needs.", "receipt": "py diff"},
        {"title": "Pick script", "verb": "Patch pick script for", "detail": "pick-agentgo mode.", "receipt": "sh diff"},
        {"title": "Generator", "verb": "Patch smart generator for", "detail": "v2 lexicon.", "receipt": "py diff"},
        {"title": "Validator", "verb": "Patch validator for", "detail": "unique title check.", "receipt": "sh diff"},
        {"title": "Build seal", "verb": "Seal build receipt for", "detail": "verify command PASS.", "receipt": "exit 0"},
        {"title": "Build retro", "verb": "Build retro for", "detail": "Next slice pointer.", "receipt": "md"},
    ],
    "w05-operate": [
        {"title": "Serve SA4", "verb": "Operate SA4 serve.sh for", "detail": ":8080 local demo.", "receipt": "curl 8080"},
        {"title": "Serve AR", "verb": "Operate agentrun serve for", "detail": ":5180 canonical.", "receipt": "curl 5180"},
        {"title": "Health", "verb": "Log health check for", "detail": "Weekly founder glance.", "receipt": "health log"},
        {"title": "Sitemap cron", "verb": "Check sitemap freshness for", "detail": "SA4 sitemap.xml date.", "receipt": "stat"},
        {"title": "Link rot", "verb": "Scan internal links for", "detail": "Sample 20 URLs.", "receipt": "scan log"},
        {"title": "localhost caveat", "verb": "Refresh localhost caveat copy for", "detail": "Buyer honesty.", "receipt": "html grep"},
        {"title": "CRM hygiene", "verb": "CRM hygiene pass for", "detail": "Remove placeholder stink.", "receipt": "crm clean"},
        {"title": "Receipt rotate", "verb": "Rotate receipt filenames for", "detail": "~/.sina/ dated.", "receipt": "json"},
        {"title": "Hub sync", "verb": "Light hub command-data sync for", "detail": "No marathon.", "receipt": "json mtime"},
        {"title": "Disk budget", "verb": "Check pack disk budget for", "detail": "plan-registry size.", "receipt": "du"},
        {"title": "Pick drain", "verb": "Log pick-agentgo drain for", "detail": "3 picks/week max Mac.", "receipt": "pick log"},
        {"title": "Incident", "verb": "File incident if blocked on", "detail": "brain-os/incidents.", "receipt": "incident md"},
        {"title": "Freeze", "verb": "Document freeze window for", "detail": "Factory FREEZE respect.", "receipt": "note"},
        {"title": "ASF gate", "verb": "Note ASF requirement for", "detail": "Public subdomain ship.", "receipt": "asf note"},
        {"title": "Ops retro", "verb": "Weekly ops retro for", "detail": "1 paragraph.", "receipt": "retro"},
        {"title": "Monitor", "verb": "Add monitor row for", "detail": "live surfaces json.", "receipt": "surfaces"},
        {"title": "Alert", "verb": "Define alert for", "detail": "gate FAIL only.", "receipt": "alert spec"},
        {"title": "Runbook", "verb": "Write runbook for", "detail": "Founder 5 steps.", "receipt": "runbook md"},
        {"title": "Ops seal", "verb": "Seal ops receipt for", "detail": "operate slice done.", "receipt": "json"},
        {"title": "Ops archive", "verb": "Archive ops log for", "detail": "receipts/.", "receipt": "archive path"},
    ],
    "w06-govern": [
        {"title": "Separation law", "verb": "Apply separation law to", "detail": "AgentGo ≠ SourceA ≠ Wil.", "receipt": "disclaimer"},
        {"title": "Cross-lane", "verb": "Run cross_lane_edit_guard for", "detail": "Before any write.", "receipt": "guard json"},
        {"title": "Terminology", "verb": "Load terminology tune for", "detail": "SOURCEA_TERMINOLOGY doc.", "receipt": "read log"},
        {"title": "Wil read", "verb": "Read Wil TERMINOLOGY for", "detail": "L3 counts read-only.", "receipt": "cite"},
        {"title": "Portfolio SSOT", "verb": "Cross-check portfolio SSOT for", "detail": "lane sections.", "receipt": "ssot grep"},
        {"title": "Planning card", "verb": "Align Planning Authority Card for", "detail": "A T1 after B proof.", "receipt": "card read"},
        {"title": "Pick law", "verb": "Document pick law for", "detail": "Revenue beats drain.", "receipt": "law md"},
        {"title": "INCIDENT-039", "verb": "Obey no validator stuck for", "detail": "Mac founder session.", "receipt": "rule"},
        {"title": "EDIT ALLOWED", "verb": "Require EDIT ALLOWED for", "detail": "Cross-desk paths.", "receipt": "guard"},
        {"title": "Registry row", "verb": "Add governance registry row for", "detail": "If needed — no duplicate SSOT.", "receipt": "registry"},
        {"title": "Supersede", "verb": "Check supersede chain for", "detail": "UP-888 · portfolio 6000.", "receipt": "manifest"},
        {"title": "Stale", "verb": "Anti-staleness sync for", "detail": "disk_live_wire.", "receipt": "sync json"},
        {"title": "Vocab", "verb": "Vocabulary unified check for", "detail": "No second prohibition law.", "receipt": "vocab"},
        {"title": "Founder form", "verb": "FORM pick if strategic for", "detail": "80 OPEN PICKs.", "receipt": "form row"},
        {"title": "ASF", "verb": "ASF checkpoint for", "detail": "Ship window only.", "receipt": "asf"},
        {"title": "Law doc", "verb": "Bump law doc version for", "detail": "AGENTGO_SA4 v2 smart.", "receipt": "md mtime"},
        {"title": "Audit", "verb": "Govern audit for", "detail": "10 spot plans.", "receipt": "audit md"},
        {"title": "Govern seal", "verb": "Seal govern slice for", "detail": "receipt.", "receipt": "json"},
        {"title": "Govern retro", "verb": "Govern retro for", "detail": "lesson.", "receipt": "md"},
        {"title": "Govern archive", "verb": "Archive govern pack for", "detail": "brain-os.", "receipt": "path"},
    ],
    "w07-document": [
        {"title": "README", "verb": "Document README for", "detail": "Pack README_LOCKED.", "receipt": "md"},
        {"title": "Index", "verb": "Update machine index for", "detail": "AGENTGO-CASE-STUDY-6000.md.", "receipt": "md"},
        {"title": "Law", "verb": "Update law doc section for", "detail": "v2 smart upgrade.", "receipt": "law md"},
        {"title": "Priority", "verb": "Append SOURCEA-PRIORITY evidence for", "detail": "dated row.", "receipt": "priority md"},
        {"title": "Offer doc", "verb": "Document offer cross-link for", "detail": "two case studies.", "receipt": "offer"},
        {"title": "CRM doc", "verb": "Document CRM fields for", "detail": "GEO ICP.", "receipt": "crm md"},
        {"title": "Architecture", "verb": "Document architecture sketch for", "detail": "SA4 tree diagram.", "receipt": "diagram"},
        {"title": "Port map", "verb": "Document port map for", "detail": "8080 · 5180 · sourcea.app.", "receipt": "table"},
        {"title": "FAQ", "verb": "Write FAQ for", "detail": "Is AgentGo SourceA?", "receipt": "faq"},
        {"title": "Glossary", "verb": "Add glossary entries for", "detail": "GEO · factory scale.", "receipt": "glossary"},
        {"title": "Lesson", "verb": "Write lesson learned for", "detail": "knowledge-library.", "receipt": "lesson"},
        {"title": "Changelog", "verb": "Hub Pro change log row for", "detail": "if app touched.", "receipt": "changelog"},
        {"title": "Onboarding", "verb": "Agent onboarding blurb for", "detail": "pick-agentgo usage.", "receipt": "blurb"},
        {"title": "Runbook", "verb": "Document runbook for", "detail": "regenerate v2.", "receipt": "runbook"},
        {"title": "API", "verb": "Document no API claims for", "detail": "localhost:3001.", "receipt": "warning"},
        {"title": "Compare doc", "verb": "Document  framing for", "detail": "fair compare.", "receipt": "doc"},
        {"title": "Receipt spec", "verb": "Document receipt schema for", "detail": "agentgo-case-study-receipt.", "receipt": "schema"},
        {"title": "Doc seal", "verb": "Seal document slice for", "detail": "complete.", "receipt": "json"},
        {"title": "Doc review", "verb": "Founder review doc for", "detail": "sign-off.", "receipt": "review"},
        {"title": "Doc archive", "verb": "Archive doc bundle for", "detail": "vault.", "receipt": "vault"},
    ],
    "w08-validate": [
        {"title": "Count", "verb": "Validate plan count for", "detail": "6000 total.", "receipt": "bash PASS"},
        {"title": "Unique", "verb": "Validate unique titles for", "detail": "2000 per angle.", "receipt": "python assert"},
        {"title": "Prompts", "verb": "Validate sample prompts exist for", "detail": "3 per angle.", "receipt": "file test"},
        {"title": "Commercial", "verb": "Run commercial copy gate for", "detail": "agentgo.html.", "receipt": "gate PASS"},
        {"title": "Depth", "verb": "Run copy depth gate for", "detail": "no filler.", "receipt": "gate PASS"},
        {"title": "Desktop", "verb": "Run desktop landing validate for", "detail": "angle B.", "receipt": "bash PASS"},
        {"title": "SA4 exists", "verb": "Validate SA4 tree exists for", "detail": "symlink ok.", "receipt": "test -d"},
        {"title": "Wil exists", "verb": "Validate Wil terminology exists for", "detail": "angle C.", "receipt": "test -f"},
        {"title": "Pick smoke", "verb": "Smoke pick-agentgo for", "detail": "3 rows.", "receipt": "pick output"},
        {"title": "Merge safe", "verb": "Validate UP-888 merge untouched for", "detail": "legacy_upgrade_id.", "receipt": "grep"},
        {"title": "Link check", "verb": "Link check case study for", "detail": "internal links.", "receipt": "link log"},
        {"title": "Separation grep", "verb": "Grep separation disclaimer for", "detail": "angle C.", "receipt": "grep PASS"},
        {"title": "No localhost lie", "verb": "Validate no false production claims for", "detail": "sign-in urls.", "receipt": "grep audit"},
        {"title": "Tier", "verb": "Validate tier assignment for", "detail": "T0 first slices.", "receipt": "registry"},
        {"title": "Phase", "verb": "Validate phase law for", "detail": "NOW 1-30.", "receipt": "registry"},
        {"title": "Gate map", "verb": "Validate receipt gates for", "detail": "landing_ship rows.", "receipt": "json"},
        {"title": "E2E skip", "verb": "Document E2E skip on Mac for", "detail": "INCIDENT-039.", "receipt": "note"},
        {"title": "CI only", "verb": "Mark CI-only validator for", "detail": "ship window.", "receipt": "ci tag"},
        {"title": "Validate seal", "verb": "Seal validate slice for", "detail": "all PASS.", "receipt": "json"},
        {"title": "Validate retro", "verb": "Validate retro for", "detail": "failures logged.", "receipt": "md"},
    ],
    "w09-integrate": [
        {"title": "Offer int", "verb": "Integrate with offer page for", "detail": "CTA + link.", "receipt": "offer html"},
        {"title": "PureFlow int", "verb": "Integrate with PureFlow case for", "detail": "two-study index.", "receipt": "cross link"},
        {"title": "CRM int", "verb": "Integrate CRM pipeline for", "detail": "GEO ICP.", "receipt": "crm"},
        {"title": "Hub int", "verb": "Integrate Hub panel row for", "detail": "optional.", "receipt": "command-data"},
        {"title": "Revenue int", "verb": "Integrate Revenue Engine for", "detail": "templates.", "receipt": "templates md"},
        {"title": "6000 int", "verb": "Cross-link portfolio-next-6000 for", "detail": "sibling pack.", "receipt": "law md"},
        {"title": "8888 int", "verb": "Cross-link portfolio-8888 if needed for", "detail": "fast-sell.", "receipt": "index"},
        {"title": "Wil int", "verb": "Integrate Wil lane doc for", "detail": "SOURCEA-PRIORITY.", "receipt": "section"},
        {"title": "Deploy int", "verb": "Integrate deploy script for", "detail": "dual paths.", "receipt": "py"},
        {"title": "Pick int", "verb": "Integrate pick-agentgo for", "detail": "plan-no-asf-run.", "receipt": "sh"},
        {"title": "Boot int", "verb": "Integrate sourcea-boot CTA for", "detail": "eval path.", "receipt": "html"},
        {"title": "Cal int", "verb": "Integrate Cal.com for", "detail": "book demo.", "receipt": "url"},
        {"title": "GitHub int", "verb": "Integrate GitHub link for", "detail": "sourcea-boot.", "receipt": "url"},
        {"title": "Film int", "verb": "Integrate commercial film for", "detail": "optional beat.", "receipt": "film json"},
        {"title": "Supabase int", "verb": "Defer Supabase row for", "detail": "cloud forge.", "receipt": "defer note"},
        {"title": "Railway int", "verb": "Defer Railway for", "detail": "ship window.", "receipt": "defer"},
        {"title": "API int", "verb": "Defer API Station for", "detail": "not localhost.", "receipt": "defer"},
        {"title": "Integrate seal", "verb": "Seal integration slice for", "detail": "wired.", "receipt": "json"},
        {"title": "Integrate test", "verb": "Integration smoke for", "detail": "manual.", "receipt": "smoke log"},
        {"title": "Integrate retro", "verb": "Integration retro for", "detail": "blockers.", "receipt": "md"},
    ],
    "w10-scale": [
        {"title": "Template", "verb": "Extract reusable template from", "detail": "case study pattern.", "receipt": "template"},
        {"title": "Playbook", "verb": "Write playbook for case study #2 for", "detail": "after PureFlow.", "receipt": "playbook"},
        {"title": "Batch", "verb": "Plan batch 3 case study for", "detail": "WitnessBC adjacency.", "receipt": "idea md"},
        {"title": "Subdomain", "verb": "Scale to subdomain for", "detail": "agentgo.sourcea.app.", "receipt": "dns plan"},
        {"title": "Full mirror", "verb": "Plan full SA4 mirror for", "detail": "defer moonshot.", "receipt": "scope md"},
        {"title": "CDN", "verb": "Plan CDN ship for", "detail": "static 1259.", "receipt": "infra note"},
        {"title": "i18n", "verb": "Defer i18n for", "detail": "EN only now.", "receipt": "defer"},
        {"title": "Enterprise", "verb": "Enterprise GEO pitch for", "detail": "moonshot.", "receipt": "pitch"},
        {"title": "Partner", "verb": "Partner channel for", "detail": "agency white-label.", "receipt": "partner md"},
        {"title": "Pricing tier", "verb": "SaaS pricing tier research for", "detail": "compare only.", "receipt": "research"},
        {"title": "Automate pick", "verb": "Automate pick drain for", "detail": "cloud worker.", "receipt": "defer"},
        {"title": "Registry v3", "verb": "Plan registry v3 for", "detail": "if grid changes.", "receipt": "idea"},
        {"title": "Metric scale", "verb": "Define scale metrics for", "detail": "pages · deals.", "receipt": "metrics"},
        {"title": "Team", "verb": "Team handoff for", "detail": "Worker INBOX.", "receipt": "inbox"},
        {"title": "Moat", "verb": "Document moat for", "detail": "receipts not pages.", "receipt": "strategy"},
        {"title": "Compete", "verb": " response for", "detail": "Peec/Profound.", "receipt": "battle card"},
        {"title": "Investor", "verb": "Investor slide bullet for", "detail": "factory scale.", "receipt": "slide"},
        {"title": "Scale seal", "verb": "Seal scale slice for", "detail": "moonshot doc.", "receipt": "json"},
        {"title": "Scale retro", "verb": "Scale retro for", "detail": "quarterly.", "receipt": "md"},
        {"title": "Scale archive", "verb": "Archive scale pack for", "detail": "roadmap.", "receipt": "roadmap row"},
    ],
}


def build_smart_task(
    angle_key: str,
    theme_id: str,
    theme_label: str,
    ws_id: str,
    ws_label: str,
    slice_n: int,
    tier: str,
    phase: str,
) -> tuple[str, str]:
    theme = THEME_CTX[theme_id]
    angle = ANGLE_CTX[angle_key]
    step = WS_PROGRESS[ws_id][slice_n - 1]

    title = f"{angle['short']} · {theme['short']} · {ws_label} · {step['title']}"
    task = (
        f"**{step['verb']}** {theme['object']}.\n\n"
        f"{step['detail']}\n\n"
        f"**Angle:** {angle['buyer']}\n"
        f"**Pure law:** {angle['pure_law']}\n"
        f"**Anti-drift:** {angle['anti']}\n"
        f"**Target path:** `{theme['path']}`\n"
        f"**Success metric:** {theme['metric']}\n"
        f"**Receipt:** {step['receipt']} before `status: done`.\n"
        f"**Phase:** {phase} · **Tier:** {tier} · **Workstream:** {ws_label}"
    )
    return title, task
