"""Polish wisdom for AgentGo case-study NOW rows (ranks 1–30 per angle) — v3."""
from __future__ import annotations

# (angle_key, priority_rank) → one thoughtful polish line appended to v3 prompts
POLISH_WISDOM: dict[tuple[str, int], str] = {
    # Angle A — Factory scale
    ("cs-a-factory", 1): "Open with the buyer question: 'Can your factory ship category scale?' — not 'we built a website.'",
    ("cs-a-factory", 2): "Hero must name three proof angles on one page — factory · dual deploy · Wil separation — before any feature list.",
    ("cs-a-factory", 3): "Add commercial + depth gates in one commit; run both validators before marking done.",
    ("cs-a-factory", 4): "OG description = one sharp outcome; cut any second sentence that repeats ALLOW/BLOCK vocabulary.",
    ("cs-a-factory", 5): "CTAs: cal.com/sourcea/proof-demo primary · offer secondary · no third competing button.",
    ("cs-a-factory", 6): "Pick demo subset: homepage + 3 trackers + 3 compare + 3 research — document paths in manifest.",
    ("cs-a-factory", 7): "Metrics block uses disk counts (1259 HTML · 593 research · 83 compare) — cite inventory receipt.",
    ("cs-a-factory", 8): "CRM seed: SaaS marketing director · not trades operator · note angle in outreach field.",
    ("cs-a-factory", 9): "Outreach A subject: 'Category surface at factory speed' — never 'another AI tool'.",
    ("cs-a-factory", 10): "Screenshot receipt: ~/.sina/agentgo-case-study-receipt-v1.json + optional PNG.",
    ("cs-a-factory", 11): "Inventory receipt: run polish v3 script — do not hand-count in chat.",
    ("cs-a-factory", 12): "Manifest JSON: schema agentgo-sa4-inventory-receipt-v1 · generated_at UTC.",
    ("cs-a-factory", 13): "Sitemap.xml line count cross-check — flag if claim drifts >5% from find count.",
    ("cs-a-factory", 14): "Tracker audit: ChatGPT · Perplexity · Gemini · Claude · Grok · Qwen minimum set.",
    ("cs-a-factory", 15): "Compare audit: fair-use framing — no 'we destroy Peec' language.",
    ("cs-a-factory", 16): "Research sample: 5 articles — reject thin SEO; keep 2 sentence quality note each.",
    ("cs-a-factory", 17): "Proof pack row optional — only if phase1 ticket still sealed logged.",
    ("cs-a-factory", 18): "Tamper demo script: 90-second procurement version — request → receipt → tamper-FAIL.",
    ("cs-a-factory", 19): "sourcea-boot CTA on case study footer — eval path for technical buyers.",
    ("cs-a-factory", 20): "PureFlow diff table on case study or linked doc — trades vs GEO column headers.",
    ("cs-a-factory", 21): "Map receipt_gate on landing-ship rows only after gates PASS.",
    ("cs-a-factory", 22): "validate-agentgo-case-study-6000 v3 — unique titles + schema_version 3.",
    ("cs-a-factory", 23): "Spot-check ranks 1–10: zero 'slice N/20' filler in titles.",
    ("cs-a-factory", 24): "Footer disclaimer on agentgo.html: AgentGo ≠ SourceA product — verbatim check.",
    ("cs-a-factory", 25): "Wil cite block read-only from TERMINOLOGY_2026 — no duplicated route counts.",
    ("cs-a-factory", 26): "Dual port curl optional — only when founder has servers running.",
    ("cs-a-factory", 27): "Seal proof only if ticket path exists — RED stays RED.",
    ("cs-a-factory", 28): "Archive prove retro under knowledge-library if lesson is reusable.",
    ("cs-a-factory", 29): "Offer page links both case studies — parity with PureFlow.",
    ("cs-a-factory", 30): "Evidence row SOURCEA-PRIORITY dated — one line outcome not process essay.",
    # Angle B — Dual deploy
    ("cs-b-dual", 1): "Run deploy script once — capture stdout paths in receipt JSON.",
    ("cs-b-dual", 2): "Desktop validator PASS required before any 'deploy proof' claim in copy.",
    ("cs-b-dual", 3): "Case study Angle B section: name ports 5180 canonical · 8080 cinematic.",
    ("cs-b-dual", 4): "Port map table: sourcea.app production vs localhost demo — never blur them.",
    ("cs-b-dual", 5): "run-recipe step 3 receipt: ~/.sina/agentgo-dual-deploy-receipt-v1.json.",
    ("cs-b-dual", 6): "PureFlow = live URL proof · AgentGo = desktop deploy proof — say both honestly.",
    ("cs-b-dual", 7): "Hub glance link optional — founder session only; no hub marathon.",
    ("cs-b-dual", 8): "CRM: agency CTO persona · screen-share deploy is the hook.",
    ("cs-b-dual", 9): "Cal script bullet: show :5180 then :8080 in 15 minutes.",
    ("cs-b-dual", 10): "PRIORITY evidence: dual deploy angle wired — date + PASS/FAIL.",
    ("cs-b-dual", 11): "Health log weekly — curl both routes when servers up.",
    ("cs-b-dual", 12): "Link rot scan on /sourcea/ paths in deployed copies.",
    ("cs-b-dual", 13): "Refresh localhost caveat sentence yearly or on ship.",
    ("cs-b-dual", 14): "CRM hygiene — remove placeholder names before outreach.",
    ("cs-b-dual", 15): "Receipt rotate dated files under ~/.sina/.",
    ("cs-b-dual", 16): "command-data sync light — read only unless EDIT ALLOWED.",
    ("cs-b-dual", 17): "Pack disk budget note in ops retro — 28MB plan-registry ok.",
    ("cs-b-dual", 18): "pick-agentgo max 3/week on Mac — INCIDENT-039.",
    ("cs-b-dual", 19): "Incident file only if blocker >1 day.",
    ("cs-b-dual", 20): "Factory FREEZE noted in runbook — no autorun bootstrap.",
    ("cs-b-dual", 21): "ASF note for public subdomain — founder decision only.",
    ("cs-b-dual", 22): "Ops retro one paragraph — blockers first.",
    ("cs-b-dual", 23): "live-surfaces json glance — factory_now_line quote.",
    ("cs-b-dual", 24): "Alert spec: gate FAIL only — no noise alerts.",
    ("cs-b-dual", 25): "Founder 5-step runbook: deploy · validate · open · screen-share · CRM.",
    ("cs-b-dual", 26): "Ops seal json when operate slice truly done.",
    ("cs-b-dual", 27): "Archive ops log to receipts/ when month closes.",
    ("cs-b-dual", 28): "Separation law grep on both desktop index.html copies.",
    ("cs-b-dual", 29): "cross_lane_edit_guard before any SA4 write.",
    ("cs-b-dual", 30): "Terminology tune read — agency voice not founder confessional.",
    # Angle C — Wil L3
    ("cs-c-wil", 1): "Extract 3 separation lines from TERMINOLOGY_2026 — quote don't paraphrase route counts.",
    ("cs-c-wil", 2): "Footer disclaimer is law — portfolio lane · not AgentGo SaaS checkout.",
    ("cs-c-wil", 3): "Ship gate criteria in prose: routes · browser · E2E · legacy zero — defer numbers to Wil doc.",
    ("cs-c-wil", 4): "SOURCEA-PRIORITY Wil section cross-link — case study as portfolio proof.",
    ("cs-c-wil", 5): "SA4/sourcea/index.html audit — remove any production sign-in implication.",
    ("cs-c-wil", 6): "Angle C section: mirror audit · crawl pipeline · L3 demo receipt vocabulary.",
    ("cs-c-wil", 7): "Manifest notes v3 polish — do not supersede portfolio-next-6000.",
    ("cs-c-wil", 8): "CRM: portfolio/strategic buyer — governance story not GEO subscription.",
    ("cs-c-wil", 9): "Offer subsection or index: case study #1 PureFlow · #2 AgentGo.",
    ("cs-c-wil", 10): "Law doc v3 section — polish script + wisdom registry.",
    ("cs-c-wil", 11): "README pack bump — schema_version 3.",
    ("cs-c-wil", 12): "AGENTGO-CASE-STUDY-6000.md index — v3 polish commands.",
    ("cs-c-wil", 13): "PRIORITY evidence row — polish complete date.",
    ("cs-c-wil", 14): "Offer doc two case studies — who each is for.",
    ("cs-c-wil", 15): "CRM doc GEO ICP fields — separate from Noetfield 613.",
    ("cs-c-wil", 16): "Architecture diagram: Wil L3 hosts SourceA lane — boxes not essay.",
    ("cs-c-wil", 17): "Port map in FAQ: production vs demo vs Wil localhost.",
    ("cs-c-wil", 18): "FAQ: 'Is AgentGo SourceA?' → No — hosted lane only.",
    ("cs-c-wil", 19): "Glossary: GEO · factory scale · portfolio lane.",
    ("cs-c-wil", 20): "Lesson to knowledge-library — separation ethics one page.",
    ("cs-c-wil", 21): "Hub changelog only if hub files touched.",
    ("cs-c-wil", 22): "Agent onboarding: pick-agentgo + polish v3 one paragraph.",
    ("cs-c-wil", 23): "Regenerate runbook: polish_agentgo_case_study_v3.py.",
    ("cs-c-wil", 24): "API doc: localhost:3001 is not production — bold warning.",
    ("cs-c-wil", 25): "Compare doc fair framing — Wil vs SourceA vs AgentGo roles.",
    ("cs-c-wil", 26): "Receipt schema agentgo-case-study-receipt-v1 documented.",
    ("cs-c-wil", 27): "Doc seal when section complete.",
    ("cs-c-wil", 28): "Founder review sign-off line in receipt.",
    ("cs-c-wil", 29): "Vault archive when bundle stable.",
    ("cs-c-wil", 30): "Govern seal — angle C NOW drain complete for this sprint.",
}


def wisdom_for(angle_key: str, priority_rank: int) -> str | None:
    return POLISH_WISDOM.get((angle_key, priority_rank))
