#!/usr/bin/env python3
"""Generate SourceA UI Pro 444-step locked upgrade plan (37 workstreams × 12 steps)."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "sourcea-ui-pro-444-upgrade-plan-v1.json"
REGISTRY_DIR = ROOT / "brain-os" / "plan-registry" / "sourcea-ui-pro-444-v1"
PROMPTS_DIR = REGISTRY_DIR / "prompts"
HUMAN_DOC = "docs/SOURCEA_UI_PRO_444_UPGRADE_PLAN_LOCKED_v1.md"
RESEARCH_DOC = "docs/SOURCEA_UI_PRO_2026_RESEARCH_REPORT_LOCKED_v1.md"

WORKSTREAMS: list[dict[str, Any]] = [
    {
        "id": "WS-01",
        "tier": "P0",
        "theme": "audit-baseline",
        "title": "UI pro audit baseline",
        "work_path": "sites/SourceA-landing/green-unified/",
        "steps": [
            "Snapshot live homepage + /sourcea/ hero parity",
            "Record LCP/CLS/INP on mobile 375px",
            "Inventory interactive surfaces (Brain, Tools, Pulse, Terminal)",
            "Map gaps vs Linear/Vercel/Raycast 2026 patterns",
            "Link mechanical gate v2 failing checks to WS owners",
            "Document stranger 5-second test script",
            "Baseline Site Pulse event counts",
            "Baseline Brain intent alignment sample",
            "Export screenshot set to reports/",
            "Write audit receipt JSON",
            "Founder sign-off on P0 scope",
            "Lock baseline SHA in plan JSON",
        ],
    },
    {
        "id": "WS-02",
        "tier": "P0",
        "theme": "positioning-ssot",
        "title": "Positioning SSOT wire",
        "work_path": "sites/SourceA-landing/green-unified/data/sourcea-positioning-v1.json",
        "steps": [
            "Read positioning v3.x one_line + denylist",
            "Sync hero H1/subcopy on / and /sourcea/",
            "Remove call-first phrases from hero bands",
            "Align footer entity Noetfield Systems Inc.",
            "Wire taxonomy box to positioning JSON",
            "curl live positioning JSON matches disk",
            "Update mechanical gate forbidden list if needed",
            "Refresh Brain bundle positioning chunk",
            "Validate brain-live stranger prompts",
            "Publish dist if copy changed",
            "Verify live H1 markers",
            "Mark WS-02 done in pulse",
        ],
    },
    {
        "id": "WS-03",
        "tier": "P0",
        "theme": "hero-live-console",
        "title": "Hero live console",
        "work_path": "sites/SourceA-landing/green-unified/sourcea-hero-console-v1.js",
        "steps": [
            "Create sourcea-hero-console-v1.js module",
            "Poll boot-proof.json for sample job",
            "Poll aeg-live.json for factory log line",
            "Render live status in #sa-biz-command",
            "Add error/offline honest state",
            "Click console chrome opens /proof/live",
            "Wire data-sa-track events",
            "Inject on founder-home only first",
            "Sync to dist/sourcea/",
            "Mobile layout console stack",
            "prefers-reduced-motion static fallback",
            "Verify no em-dash placeholders in console",
        ],
    },
    {
        "id": "WS-04",
        "tier": "P0",
        "theme": "forge-hero-embed",
        "title": "Forge hero embed",
        "work_path": "sites/SourceA-landing/green-unified/founder-home.html",
        "steps": [
            "Add embed=1 terminal route guard",
            "Iframe or shadow embed 340px hero column",
            "Lazy-load embed after LCP",
            "PostMessage height sync",
            "Offline banner when worker down",
            "CTA fallback to full terminal page",
            "CSP/frame ancestors check",
            "Mobile: collapse to tap-to-open",
            "Track forge_hero_embed_open",
            "Security review no auth leak",
            "dist sync",
            "Live verify send one prompt",
        ],
    },
    {
        "id": "WS-05",
        "tier": "P0",
        "theme": "trust-ssr",
        "title": "Trust stats SSR (RI-2)",
        "work_path": "sites/SourceA-landing/green-unified/founder-home.html",
        "steps": [
            "Read trust-signals-public-v1.json counts",
            "Inline jobs verified in HTML not JS-only",
            "Inline governance PASS in HTML",
            "Inline github stars fallback",
            "Remove em-dash placeholders from view-source",
            "Hydration upgrades not replaces text",
            "Mechanical placeholder_counter PASS",
            "Apply to index.html subsite",
            "Apply to proof/live trust bar",
            "dist build",
            "Live crawl audit PASS",
            "Receipt in reports/",
        ],
    },
    {
        "id": "WS-06",
        "tier": "P0",
        "theme": "engine-chips",
        "title": "Engine chip storytelling",
        "work_path": "sites/SourceA-landing/green-unified/sourcea-hero-console-v1.js",
        "steps": [
            "Convert Plan→Commit chips to buttons",
            "Tab panel per engine stage",
            "Map stages to receipt fields",
            "Animate active chip state",
            "Keyboard roving tabindex",
            "ARIA tablist pattern",
            "Sync with scroll story hook",
            "Reduced motion instant swap",
            "Track engine_chip_select",
            "Copy per stage from positioning",
            "dist sync",
            "Stranger test 30s comprehension",
        ],
    },
    {
        "id": "WS-07",
        "tier": "P0",
        "theme": "brain-hero-prompt",
        "title": "Brain hero prompt bar",
        "work_path": "sites/SourceA-landing/green-unified/sourcea-chatbot.js",
        "steps": [
            "Add hero inline prompt input",
            "Submit opens Brain with message",
            "Suggest chips: pricing, terminal, proof",
            "Page context page_path=founder-home",
            "Mobile stack below CTAs",
            "Do not duplicate FAB",
            "Honor execution-first greet",
            "Offline sync banner integration",
            "Track brain_hero_prompt_submit",
            "dist sync",
            "brain-live validator PASS",
            "Live stranger prompt test",
        ],
    },
    {
        "id": "WS-08",
        "tier": "P0",
        "theme": "home-unify",
        "title": "Home route unify",
        "work_path": "sites/SourceA-landing/green-unified/index.html",
        "steps": [
            "Diff / vs /sourcea/ index heroes",
            "Pick founder-home as canonical",
            "Redirect or mirror content",
            "Unify nav fingerprints",
            "Unify primary CTA order",
            "Unify trust bar markup",
            "Unify meta og tags",
            "UP-DR-04 markers live",
            "dist sync",
            "E2E both routes",
            "Mechanical gate disk PASS",
            "Document route map",
        ],
    },
    {
        "id": "WS-09",
        "tier": "P0",
        "theme": "cta-law",
        "title": "Primary CTA law",
        "work_path": "sites/SourceA-landing/green-unified/data/sourcea-landing-cta-v1.json",
        "steps": [
            "Forge Terminal first on money pages",
            "Talk to human last + demoted",
            "Remove Book proof demo primary",
            "data-sa-primary-cta single per hero",
            "Sticky mobile CTA bar",
            "Tools dock book-demo bottom",
            "Cal overlay optional only",
            "Track cta_click hierarchy",
            "Apply pricing.html",
            "Apply offer.html",
            "dist sync",
            "Validator CTA order check",
        ],
    },
    {
        "id": "WS-10",
        "tier": "P1",
        "theme": "bento-grid",
        "title": "Bento proof grid",
        "work_path": "sites/SourceA-landing/green-unified/founder-home.html",
        "steps": [
            "Design 6-tile asymmetric grid",
            "Tile: Forge Terminal screenshot",
            "Tile: Live receipt",
            "Tile: Eval/boot",
            "Tile: Pricing",
            "Tile: Factory catalog",
            "Tile: Brain chat",
            "Hover lift + focus ring",
            "Each tile links real URL",
            "prefers-reduced-motion",
            "Mobile 2-col stack",
            "dist + live verify",
        ],
    },
    {
        "id": "WS-11",
        "tier": "P1",
        "theme": "scroll-story",
        "title": "Scroll-driven story",
        "work_path": "sites/SourceA-landing/green-unified/sourcea-scroll-story-v1.js",
        "steps": [
            "Create scroll-story module",
            "Pin hero console on scroll",
            "Step 1 Plan copy block",
            "Step 2 Control",
            "Step 3 Execute",
            "Step 4 Verify",
            "Step 5 Commit",
            "IntersectionObserver thresholds",
            "Reduced motion skip pin",
            "Track scroll_story_step",
            "dist sync",
            "Mobile shortened path",
        ],
    },
    {
        "id": "WS-12",
        "tier": "P1",
        "theme": "pulse-strip",
        "title": "Site Pulse public strip",
        "work_path": "sites/SourceA-landing/green-unified/sourcea-site-pulse-v1.js",
        "steps": [
            "GET /api/site/stats/v1 consumer",
            "Anon aggregate display strip",
            "Copy: builders verified this week",
            "Fallback when stats unavailable",
            "Place below hero trust",
            "No PII in strip",
            "Rate limit client poll",
            "Track pulse_strip_impression",
            "Style match sa-trust-bar",
            "dist sync",
            "Worker CORS check",
            "Live verify strip renders",
        ],
    },
    {
        "id": "WS-13",
        "tier": "P1",
        "theme": "command-palette",
        "title": "Command palette ⌘K",
        "work_path": "sites/SourceA-landing/green-unified/sourcea-cmdk-v1.js",
        "steps": [
            "Create cmdk overlay component",
            "Fuzzy search routes from sitemap",
            "Actions: terminal, start, eval, brain",
            "Keyboard ⌘K Ctrl+K",
            "Escape close focus trap",
            "Recent routes localStorage",
            "Track cmdk_open/select",
            "Inject all main templates",
            "dist sync",
            "A11y audit",
            "Mobile long-press alt",
            "Document shortcuts",
        ],
    },
    {
        "id": "WS-14",
        "tier": "P1",
        "theme": "persona-hero",
        "title": "Persona hero routing",
        "work_path": "sites/SourceA-landing/green-unified/sourcea-segment-router-v1.js",
        "steps": [
            "Parse ?seg= and UTM lane",
            "Swap H1 from positioning variants",
            "Swap primary CTA target",
            "Persist segment sessionStorage",
            "Wire site-interact segments",
            "Agency → case studies",
            "Startup → /start",
            "Cursor → terminal",
            "Track segment_hero_view",
            "dist sync",
            "Test 4 segments live",
            "No flash wrong copy",
        ],
    },
    {
        "id": "WS-15",
        "tier": "P1",
        "theme": "tools-dock",
        "title": "Tools dock promotion",
        "work_path": "sites/SourceA-landing/green-unified/data/sourcea-site-interact-v1.json",
        "steps": [
            "Promote guided modal first visit",
            "Execution_first flag enforce",
            "Demote book-demo skill",
            "Add proof-first chip",
            "Dock z-index above content",
            "Mobile bottom sheet",
            "Track tools_dock_open",
            "Sync config version bump",
            "dist sync",
            "Stranger finds dock <3s",
            "Align with cmdk actions",
            "Validator interact config",
        ],
    },
    {
        "id": "WS-16",
        "tier": "P1",
        "theme": "guided-onboarding",
        "title": "Guided onboarding",
        "work_path": "sites/SourceA-landing/green-unified/sourcea-site-interact-v1.js",
        "steps": [
            "What brings you here modal",
            "One question routing",
            "No calendar in guided path",
            "guided_once_per_session",
            "Skip restores dock only",
            "Track guided_complete",
            "A11y dialog focus",
            "Mobile full-screen sheet",
            "dist sync",
            "Test 5 segment paths",
            "Analytics funnel",
            "Document copy SSOT",
        ],
    },
    {
        "id": "WS-17",
        "tier": "P1",
        "theme": "sku-landers",
        "title": "SKU commercial landers",
        "work_path": "sites/SourceA-landing/green-unified/",
        "steps": [
            "operating-brain-install contact surface",
            "ai-value-governance contact surface",
            "enterprise-ai-control-plane contact",
            "Embed Brain on SKU pages",
            "hello@sourcea.app visible",
            "Primary CTA to /start",
            "mechanical no_contact_surface PASS",
            "og:image per UP-DR-10",
            "dist sync",
            "Live E2E SKU routes",
            "Receipt hygiene",
            "Mark SKU lane done",
        ],
    },
    {
        "id": "WS-18",
        "tier": "P1",
        "theme": "pricing-ux",
        "title": "Pricing surface UX",
        "work_path": "sites/SourceA-landing/green-unified/pricing.html",
        "steps": [
            "Canonical tier table visible",
            "Build/Rent/Own clarity",
            "No {ENTITY} footer",
            "Interactive tier compare toggle",
            "Forge CTA on pricing",
            "price_drift gate alignment",
            "Mobile tier cards",
            "Track pricing_view",
            "dist sync",
            "UP-DR-05 verify",
            "Brain pricing chip in-chat",
            "Live pricing markers",
        ],
    },
    {
        "id": "WS-19",
        "tier": "P1",
        "theme": "proof-receipt",
        "title": "Proof & receipt UX",
        "work_path": "sites/SourceA-landing/green-unified/proof/",
        "steps": [
            "UP-DR-08 what this proves block",
            "Embed receipt on start.html",
            "proof/live terminal panel",
            "Export PDF link visible",
            "Verdict color system",
            "No call-first proof copy",
            "Track proof_view",
            "dist sync",
            "Sample pack download",
            "Mechanical gate proof pages",
            "Live receipt JSON valid",
            "Stranger verifies in 5min",
        ],
    },
    {
        "id": "WS-20",
        "tier": "P1",
        "theme": "forge-terminal",
        "title": "Forge Terminal polish",
        "work_path": "sites/SourceA-landing/green-unified/sourcea/forge/terminal.html",
        "steps": [
            "UP-DR-02 online path green",
            "Connecting state fix",
            "Offline forge@ fallback",
            "data-sa-proof-cta markers",
            "Workspace link clarity",
            "Mobile terminal layout",
            "Track terminal_send",
            "dist sync",
            "brain-live ide prompt",
            "Embed mode polish",
            "Performance send latency",
            "Live demo script",
        ],
    },
    {
        "id": "WS-21",
        "tier": "P1",
        "theme": "eval-boot",
        "title": "Eval & sourcea-boot",
        "work_path": "sites/SourceA-landing/green-unified/eval.html",
        "steps": [
            "UP-DR-01 PyPI honesty",
            "Inline try eval CTA",
            "Copy install vs GitHub",
            "Link from hero eval button",
            "Developer lane Brain routing",
            "Track eval_page_view",
            "dist sync",
            "probe_sourcea_boot PASS",
            "Code snippet hero optional",
            "Mobile eval layout",
            "Link kernel docs",
            "Live eval markers",
        ],
    },
    {
        "id": "WS-22",
        "tier": "P1",
        "theme": "start-intake",
        "title": "Start intake UX",
        "work_path": "sites/SourceA-landing/green-unified/start.html",
        "steps": [
            "UP-DR-03 intake submit",
            "UP-DR-06 privacy note",
            "5-question flow polish",
            "Success reference ID",
            "Receipt embed section",
            "Mobile form UX",
            "Track intake_submit",
            "dist sync",
            "verify_mvp_intake PASS",
            "Supabase row proof",
            "Error states honest",
            "Post-submit next steps",
        ],
    },
    {
        "id": "WS-23",
        "tier": "P2",
        "theme": "factory-catalog",
        "title": "Factory catalog interactive",
        "work_path": "sites/SourceA-landing/green-unified/factories/",
        "steps": [
            "Factory card hover states",
            "Live status badges",
            "Filter by tier A/B/C",
            "Link to try demos",
            "products-catalog JSON wire",
            "Track factory_card_click",
            "dist sync",
            "Mobile horizontal scroll",
            "SEO factory pages",
            "Brain factory intent",
            "Mechanical copy scan",
            "Live factories index",
        ],
    },
    {
        "id": "WS-24",
        "tier": "P2",
        "theme": "video-hover",
        "title": "Video-on-hover cards",
        "work_path": "sites/SourceA-landing/green-unified/sourcea-home.css",
        "steps": [
            "Select 6 factory WebM loops",
            "Lazy load on hover",
            "Poster image fallback",
            "prefers-reduced-motion static",
            "Bandwidth cap mobile off",
            "Track video_hover_play",
            "dist sync",
            "CDN path under /assets/",
            "LCP regression check",
            "Alt text per factory",
            "Factory hero section",
            "Live hover test",
        ],
    },
    {
        "id": "WS-25",
        "tier": "P1",
        "theme": "mobile-pro",
        "title": "Mobile pro layout",
        "work_path": "sites/SourceA-landing/green-unified/sourcea.css",
        "steps": [
            "375px hero regression",
            "Brain head-main mobile safe",
            "Sticky CTA not covering chat",
            "Touch target 44px",
            "Forge mobile embed tap",
            "Tools dock bottom safe area",
            "validate-forge-mobile PASS",
            "dist sync",
            "iOS Safari test",
            "Android Chrome test",
            "Landscape fold",
            "Mobile pulse FAB",
        ],
    },
    {
        "id": "WS-26",
        "tier": "P1",
        "theme": "motion-a11y",
        "title": "Motion & a11y",
        "work_path": "sites/SourceA-landing/green-unified/sourcea-home.css",
        "steps": [
            "prefers-reduced-motion global",
            "Pause aurora when reduced",
            "Focus visible rings",
            "Skip link works",
            "Color contrast AA",
            "aria-live on console",
            "No autoplay audio",
            "Tab order audit",
            "Screen reader hero",
            "dist sync",
            "Lighthouse a11y 90+",
            "Document motion policy",
        ],
    },
    {
        "id": "WS-27",
        "tier": "P1",
        "theme": "performance",
        "title": "Performance LCP",
        "work_path": "scripts/build_sourcea_vercel_output_v1.py",
        "steps": [
            "LCP target under 2.5s",
            "Defer aurora on mobile",
            "Font subset preload",
            "content-visibility sections",
            "Image width/height attrs",
            "Preconnect brain worker",
            "Third-party script audit",
            "dist size budget",
            "Track Web Vitals RUM",
            "Nitro-style URL test optional",
            "CI lighthouse smoke",
            "Receipt LCP score",
        ],
    },
    {
        "id": "WS-28",
        "tier": "P2",
        "theme": "og-share",
        "title": "OG & share cards",
        "work_path": "sites/SourceA-landing/green-unified/",
        "steps": [
            "UP-DR-10 og:image site-wide",
            "1200x630 asset",
            "Per-route og:title",
            "twitter:card summary_large",
            "Proof URL share preview",
            "Mechanical SM-2 PASS",
            "dist sync",
            "LinkedIn debugger",
            "Slack unfurl test",
            "Canonical URLs",
            "hreflang if needed",
            "Share gate validator",
        ],
    },
    {
        "id": "WS-29",
        "tier": "P1",
        "theme": "accessibility",
        "title": "Accessibility hardening",
        "work_path": "sites/SourceA-landing/green-unified/",
        "steps": [
            "Heading hierarchy audit",
            "Form labels start intake",
            "Error announcements",
            "Dialog aria-modal",
            "Live region spam guard",
            "Keyboard cmdk + dock",
            "High contrast mode",
            "Reduced transparency",
            "dist sync",
            "axe scan zero critical",
            "Document a11y statement",
            "Retest quarterly",
        ],
    },
    {
        "id": "WS-30",
        "tier": "P0",
        "theme": "mechanical-gate",
        "title": "Mechanical gate alignment",
        "work_path": "data/sourcea-ui-mechanical-gate-v1.json",
        "steps": [
            "Map UP-UI steps to gate checks",
            "RI-2 placeholder_counter green",
            "Entity consistency green",
            "SKU contact FAIL cleared",
            "Receipt reports/ only",
            "Disk scan PASS pre-ship",
            "Live E2E audit trend",
            "Wire run-recipe.sh",
            "Document verify law",
            "Agent fixing ≠ PASS rule",
            "Pulse mechanical count",
            "Gate version 1.2+ locked",
        ],
    },
    {
        "id": "WS-31",
        "tier": "P1",
        "theme": "brain-chat-ux",
        "title": "Brain chat UX",
        "work_path": "sites/SourceA-landing/green-unified/sourcea-chatbot.js",
        "steps": [
            "Workers AI status field fix",
            "In-chat chips no hard nav",
            "Citation links public only",
            "Low confidence prefix UX",
            "Mobile brain panel",
            "Page context injection",
            "Track brain_turn",
            "dist sync",
            "brain-live PASS",
            "Retrieval curated boost",
            "SKU page brain embed",
            "Stranger 3-question test",
        ],
    },
    {
        "id": "WS-32",
        "tier": "P2",
        "theme": "agentic-demo",
        "title": "Agentic demo mode",
        "work_path": "cloud/workers/sourcea-brain-chat-v1/",
        "steps": [
            "Guided demo thread schema",
            "Step prompts terminal+receipt",
            "Freeform Q mid-demo",
            "CRM-less analytics only",
            "Demo mode header flag",
            "Track agentic_demo_start",
            "Worker deploy",
            "Landing CTA Try guided demo",
            "Fallback retrieval-only",
            "brain-core gate staging",
            "Privacy stranger-safe",
            "Live agentic path test",
        ],
    },
    {
        "id": "WS-33",
        "tier": "P2",
        "theme": "founder-analytics",
        "title": "Founder analytics UI",
        "work_path": "agent-control-panel/",
        "steps": [
            "Site Pulse dashboard page",
            "Pageview heat list",
            "Feedback theme rollup",
            "Forge embed clicks",
            "Brain turn counts",
            "Export CSV",
            "Auth founder only",
            "Hub embed optional",
            "Track dashboard_view",
            "No stranger PII",
            "KV read API",
            "Document ops runbook",
        ],
    },
    {
        "id": "WS-34",
        "tier": "P2",
        "theme": "ecosystem-map",
        "title": "Ecosystem footer map",
        "work_path": "sites/SourceA-landing/green-unified/",
        "steps": [
            "UP-DR-09 relation map",
            "SourceA vs Forge vs Brain",
            "Noetfield link",
            "Contract SKU links",
            "Footer nav fingerprint",
            "Mobile footer accordion",
            "Track footer_link_click",
            "dist sync",
            "nav_fingerprint gate",
            "Legal entity consistent",
            "Sitemap alignment",
            "Live footer verify",
        ],
    },
    {
        "id": "WS-35",
        "tier": "P1",
        "theme": "nav-unify",
        "title": "Nav fingerprint unify",
        "work_path": "sites/SourceA-landing/green-unified/",
        "steps": [
            "Max 2 nav fingerprints",
            "Marketing shell vs app shell",
            "/sourcea/ subsite align",
            "Sign in placement",
            "Mobile nav drawer",
            "Active state data-sa-nav",
            "Breadcrumb optional",
            "Track nav_click",
            "dist sync",
            "Mechanical nav check",
            "Live nav E2E",
            "Document nav SSOT",
        ],
    },
    {
        "id": "WS-36",
        "tier": "P0",
        "theme": "entity-legal",
        "title": "Entity & legal consistency",
        "work_path": "sites/SourceA-landing/green-unified/",
        "steps": [
            "No {ENTITY} anywhere",
            "Footer Noetfield Systems Inc.",
            "Privacy links on intake",
            "Security page honest",
            "No fake certifications",
            "mailto hello@sourcea.app",
            "dist sync",
            "entity_consistency PASS",
            "Pricing footer match",
            "SKU footers match",
            "Brain no internal leaks",
            "Live crawl verify",
        ],
    },
    {
        "id": "WS-37",
        "tier": "P0",
        "theme": "ship-gate",
        "title": "Ship gate & validator",
        "work_path": "scripts/validate-sourcea-ui-pro-444-v1.sh",
        "steps": [
            "Create pulse script 444 count",
            "Create validator shell",
            "Wire run-recipe optional",
            "Publish landing pipeline",
            "Cloudflare cache purge",
            "Live homepage 200",
            "Mechanical PASS",
            "brain-live PASS",
            "UP-DR pulse alignment",
            "Founder 5-min stranger test",
            "Receipt WARM_COMMERCIAL_READY",
            "Lock plan version 1.0.0",
        ],
    },
]


def build_steps() -> list[dict[str, Any]]:
    steps: list[dict[str, Any]] = []
    n = 0
    for ws in WORKSTREAMS:
        for i, title in enumerate(ws["steps"], start=1):
            n += 1
            steps.append(
                {
                    "id": f"UP-UI-{n:03d}",
                    "ws_id": ws["id"],
                    "ws_step": i,
                    "tier": ws["tier"],
                    "theme": ws["theme"],
                    "ws_title": ws["title"],
                    "title": title,
                    "work_path": ws["work_path"],
                    "status": "open",
                    "verify": f"bash scripts/validate-sourcea-ui-pro-444-v1.sh --step UP-UI-{n:03d}",
                }
            )
    if n != 444:
        raise SystemExit(f"expected 444 steps, got {n}")
    return steps


def build_registry(steps: list[dict[str, Any]]) -> dict[str, Any]:
    ws_index = []
    for ws in WORKSTREAMS:
        ws_steps = [s for s in steps if s["ws_id"] == ws["id"]]
        ws_index.append(
            {
                "id": ws["id"],
                "tier": ws["tier"],
                "theme": ws["theme"],
                "title": ws["title"],
                "work_path": ws["work_path"],
                "step_ids": [s["id"] for s in ws_steps],
                "prompt_path": f"brain-os/plan-registry/sourcea-ui-pro-444-v1/prompts/{ws['id'].lower()}.md",
            }
        )
    return {
        "schema": "sourcea-ui-pro-444-plan-registry-v1",
        "version": "1.0.0",
        "saved_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "workstream_count": len(WORKSTREAMS),
        "step_count": 444,
        "ssot": "data/sourcea-ui-pro-444-upgrade-plan-v1.json",
        "human_doc": HUMAN_DOC,
        "research_doc": RESEARCH_DOC,
        "pulse_script": "scripts/sourcea_ui_pro_444_pulse_v1.py",
        "validator": "scripts/validate-sourcea-ui-pro-444-v1.sh",
        "generator": "scripts/generate_sourcea_ui_pro_444_plan_v1.py",
        "one_law": "One UP-UI step = one bounded landing commit · hero interactive before decorative motion",
        "critical_path": ["UP-UI-001", "UP-UI-025", "UP-UI-037", "UP-UI-073", "UP-UI-444"],
        "workstreams": ws_index,
    }


def write_prompt_stubs() -> None:
    PROMPTS_DIR.mkdir(parents=True, exist_ok=True)
    for ws in WORKSTREAMS:
        path = PROMPTS_DIR / f"{ws['id'].lower()}.md"
        if path.is_file():
            continue
        body = f"""# {ws['id']} — {ws['title']}

**Tier:** {ws['tier']} · **Theme:** {ws['theme']}  
**Path:** `{ws['work_path']}`

## Law

Execution-first · product-is-the-hero · no call-first CTAs.

## Steps (12)

"""
        for i, step in enumerate(ws["steps"], start=1):
            body += f"{i}. {step}\n"
        body += "\n## Verify\n\n`bash scripts/validate-sourcea-ui-pro-444-v1.sh`\n"
        path.write_text(body, encoding="utf-8")


def main() -> int:
    steps = build_steps()
    row = {
        "schema": "sourcea-ui-pro-444-upgrade-plan-v1",
        "version": "1.0.0",
        "saved_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "locked": True,
        "baseline": "PRODUCT_BETA_UI",
        "target": "WARM_COMMERCIAL_INTERACTIVE",
        "research_doc": RESEARCH_DOC,
        "human_doc": HUMAN_DOC,
        "one_law": "444 steps · 37 workstreams · product-is-the-hero · execution-first · stranger tests in browser",
        "motor_note": "Optional queue via client-proof; default Worker INBOX bounded landing lane",
        "benchmark": "Linear · Vercel · Raycast · Clerk · Neon patterns July 2026",
        "skill_ref": ".cursor/skills/sourcea-landing-agentic-ui/SKILL.md",
        "mechanical_gate": "data/sourcea-ui-mechanical-gate-v1.json",
        "up_dr_alignment": [
            "UP-DR-04",
            "UP-DR-05",
            "UP-DR-08",
            "UP-DR-09",
            "UP-DR-10",
        ],
        "wave_map": {
            "W1_P0_HERO": list(range(1, 109)),
            "W2_P1_INTERACTIVE": list(range(109, 301)),
            "W3_P2_SCALE": list(range(301, 433)),
            "W4_SHIP": list(range(433, 445)),
        },
        "workstream_count": 37,
        "step_count": 444,
        "workstreams": WORKSTREAMS,
        "steps": steps,
        "pulse_script": "scripts/sourcea_ui_pro_444_pulse_v1.py",
        "validator": "scripts/validate-sourcea-ui-pro-444-v1.sh",
        "generator": "scripts/generate_sourcea_ui_pro_444_plan_v1.py",
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(row, indent=2) + "\n", encoding="utf-8")
    REGISTRY_DIR.mkdir(parents=True, exist_ok=True)
    (REGISTRY_DIR / "REGISTRY.json").write_text(
        json.dumps(build_registry(steps), indent=2) + "\n", encoding="utf-8"
    )
    write_prompt_stubs()
    print(json.dumps({"ok": True, "steps": len(steps), "out": str(OUT.relative_to(ROOT))}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
