"""Canonical paths for tier-0 governance docs (batch 3.5 taxonomy)."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LAW = ROOT / "brain-os" / "law"
SYSTEM = ROOT / "brain-os" / "system"
ENTRY = LAW / "entry"
ENFORCEMENT = LAW / "enforcement"
INCIDENTS = ROOT / "brain-os" / "incidents"

COMMERCIAL_SSOT = LAW / "SOURCEA_UNIFIED_PORTFOLIO_COMMERCIAL_SSOT_LOCKED_v3.1.md"
GOVERNANCE_ENTRY = ENTRY / "SINA_GOVERNANCE_ENTRY_LOCKED_v1.md"
AUTHORITY_INDEX = SYSTEM / "SINA_AUTHORITY_INDEX_MAP_LOCKED_v1.md"
SINA_OS_SSOT = LAW / "SINA_OS_SSOT_LOCKED.md"
NO_FAKE_PROGRESS = LAW / "SOURCEA_NO_FAKE_PROGRESS_ENTERPRISE_SHIP_LOCKED_v1.md"
REPO_SSOT = LAW / "SOURCEA_REPO_SSOT_LOCKED.md"
EXECUTION_LAW = LAW / "SOURCEA_EXECUTION_LAW_LOCKED_v1.md"
LAW_ROOT_INDEX = ENTRY / "LAW_ROOT_INDEX_LOCKED_v1.md"
WORKER_EVIDENCE_LAW = ENFORCEMENT / "WORKER_FULL_ROUND_EVIDENCE_ENFORCEMENT_LOCKED_v1.md"

# Batch 5a — SOURCEA_* law docs (canonical under brain-os/law/)
def law_doc(name: str) -> Path:
    """Resolve a LOCKED law filename under brain-os/law/."""
    return LAW / name


LIVE_FOUNDER_FORM = law_doc("SOURCEA_LIVE_FOUNDER_DECISION_FORM_LOCKED_v1.md")
FOUNDER_MESSAGE_NORM = law_doc("SOURCEA_FOUNDER_MESSAGE_NORMALIZATION_LOCKED_v1.md")
FOUNDER_TERMINOLOGY = law_doc("SOURCEA_FOUNDER_MACHINE_TERMINOLOGY_DICTIONARY_LOCKED_v1.md")
FOUNDER_DIRECTION_TERMS = law_doc("SOURCEA_FOUNDER_DIRECTION_TERMINOLOGY_LOCKED_v1.md")
SUPER_FAST_HUB = law_doc("SOURCEA_SUPER_FAST_HUB_LOCKED_v1.md")
AGENTIC_LAYER_STACK = law_doc("SOURCEA_AGENTIC_LAYER_STACK_LOCKED_v2.md")
LIVE_ONGOING_PROMPTS = law_doc("SOURCEA_LIVE_ONGOING_PROMPTS_LOCKED_v1.md")
PHASE_STRICT_RUN_INBOX = law_doc("SOURCEA_PHASE_STRICT_RUN_INBOX_LOCKED_v1.md")
OPENROUTER_ACTIVATION_QUEUE = law_doc("SOURCEA_OPENROUTER_ACTIVATION_QUEUE_LOCKED_v1.md")
INCIDENT_FIX_OWNERSHIP = law_doc("SOURCEA_INCIDENT_FIX_OWNERSHIP_GOVERNANCE_HARDENING_LOCKED_v1.md")
RESULT_DRIVEN_DISCUSSION = law_doc("SOURCEA_RESULT_DRIVEN_DISCUSSION_POLICY_LOCKED_v1.md")
CURSOR_RULES_MAP = law_doc("SOURCEA_CURSOR_RULES_AND_SKILLS_MAP_LOCKED_v2.md")
AUTHORITY_REGISTRY_GOV = law_doc("SOURCEA_AUTHORITY_REGISTRY_GOV_UNIFY_BATCH_2026-06-11_LOCKED_v1.md")
S10_ETERNAL_AUDIT = law_doc("SOURCEA_S10_ETERNAL_SELF_HEAL_AUDIT_LOCKED_v1.md")
REF_ARCH_CONSTELLATION = law_doc("SOURCEA_REFERENCE_ARCHITECTURE_CONSTELLATION_LOCKED_v1.md")
FIVE_STEP_BLUEPRINT = law_doc("SOURCEA_FIVE_STEP_AUTONOMOUS_PROGRESS_BLUEPRINT_LOCKED_v1.md")
FORK_MACHINE = law_doc("SOURCEA_COMPLEX_SITUATION_FORK_MACHINE_LOCKED_v1.md")
INTEGRITY_PLAYBOOK = law_doc("SOURCEA_SYSTEM_INTEGRITY_100_STEP_PLAYBOOK_LOCKED_v1.md")
INTEGRITY_SESSION_LOG = law_doc("SOURCEA_SYSTEM_INTEGRITY_SESSION_LOG_v1.md")

REL_LAW_PREFIX = "brain-os/law/"
REL_COMMERCIAL_SSOT = "brain-os/law/SOURCEA_UNIFIED_PORTFOLIO_COMMERCIAL_SSOT_LOCKED_v3.1.md"
REL_GOVERNANCE_ENTRY = "brain-os/law/entry/SINA_GOVERNANCE_ENTRY_LOCKED_v1.md"
REL_AUTHORITY_INDEX = "brain-os/system/SINA_AUTHORITY_INDEX_MAP_LOCKED_v1.md"
REL_SINA_OS_SSOT = "brain-os/law/SINA_OS_SSOT_LOCKED.md"
REL_NO_FAKE_PROGRESS = "brain-os/law/SOURCEA_NO_FAKE_PROGRESS_ENTERPRISE_SHIP_LOCKED_v1.md"
