"""Canonical paths for tier-0 governance docs (batch 3.5 taxonomy)."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LAW = ROOT / "brain-os" / "law"
SYSTEM = ROOT / "brain-os" / "system"
ENTRY = LAW / "entry"
ENFORCEMENT = LAW / "enforcement"
INCIDENTS = ROOT / "brain-os" / "incidents"

COMMERCIAL_SSOT = LAW / "SOURCEA_UNIFIED_PORTFOLIO_COMMERCIAL_SSOT_LOCKED_v3.1.md"
GOVERNANCE_ENTRY = ENTRY / "SINA_GOVERNANCE_ENTRY_LOCKED_v1.md"
AUTHORITY_INDEX = SYSTEM / "SINA_AUTHORITY_INDEX_MAP_LOCKED_v1.md"
SINA_OS_SSOT = LAW / "SINA_OS_SSOT_LOCKED.md"
NO_FAKE_PROGRESS = LAW / "SOURCEA_NO_FAKE_PROGRESS_ENTERPRISE_SHIP_LOCKED_v1.md"
REPO_SSOT = LAW / "SOURCEA_REPO_SSOT_LOCKED.md"
EXECUTION_LAW = LAW / "SOURCEA_EXECUTION_LAW_LOCKED_v1.md"
LAW_ROOT_INDEX = ENTRY / "LAW_ROOT_INDEX_LOCKED_v1.md"
WORKER_EVIDENCE_LAW = ENFORCEMENT / "WORKER_FULL_ROUND_EVIDENCE_ENFORCEMENT_LOCKED_v1.md"

REL_COMMERCIAL_SSOT = "brain-os/law/SOURCEA_UNIFIED_PORTFOLIO_COMMERCIAL_SSOT_LOCKED_v3.1.md"
REL_GOVERNANCE_ENTRY = "brain-os/law/entry/SINA_GOVERNANCE_ENTRY_LOCKED_v1.md"
REL_AUTHORITY_INDEX = "brain-os/system/SINA_AUTHORITY_INDEX_MAP_LOCKED_v1.md"
REL_SINA_OS_SSOT = "brain-os/law/SINA_OS_SSOT_LOCKED.md"
REL_NO_FAKE_PROGRESS = "brain-os/law/SOURCEA_NO_FAKE_PROGRESS_ENTERPRISE_SHIP_LOCKED_v1.md"
