"""Canonical paths for tier-0 governance docs (batch 3.5 taxonomy)."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LAW = ROOT / "brain-os" / "law"
SYSTEM = ROOT / "brain-os" / "system"
ENTRY = LAW / "entry"
ENFORCEMENT = LAW / "enforcement"
INCIDENTS = ROOT / "brain-os" / "incidents"
WTM = ROOT / "brain-os" / "wtm"

COMMERCIAL_SSOT = LAW / "SOURCEA_UNIFIED_PORTFOLIO_COMMERCIAL_SSOT_LOCKED_v3.1.md"
GOVERNANCE_ENTRY = ENTRY / "SINA_GOVERNANCE_ENTRY_LOCKED_v1.md"
AUTHORITY_INDEX = SYSTEM / "SINA_AUTHORITY_INDEX_MAP_LOCKED_v1.md"
SINA_OS_SSOT = LAW / "SINA_OS_SSOT_LOCKED.md"
NO_FAKE_PROGRESS = LAW / "SOURCEA_NO_FAKE_PROGRESS_ENTERPRISE_SHIP_LOCKED_v1.md"
REPO_SSOT = LAW / "SOURCEA_REPO_SSOT_LOCKED.md"
EXECUTION_LAW = LAW / "SOURCEA_EXECUTION_LAW_LOCKED_v1.md"
LAW_ROOT_INDEX = ENTRY / "LAW_ROOT_INDEX_LOCKED_v1.md"
WORKER_EVIDENCE_LAW = ENFORCEMENT / "WORKER_FULL_ROUND_EVIDENCE_ENFORCEMENT_LOCKED_v1.md"

# Batch 5a — SOURCEA_* law docs (canonical under brain-os/law/)
def law_doc(name: str) -> Path:
    """Resolve a LOCKED law filename under brain-os/law/."""
    return LAW / name


LIVE_FOUNDER_FORM = law_doc("SOURCEA_LIVE_FOUNDER_DECISION_FORM_LOCKED_v1.md")
FOUNDER_MESSAGE_NORM = law_doc("SOURCEA_FOUNDER_MESSAGE_NORMALIZATION_LOCKED_v1.md")
FOUNDER_TERMINOLOGY = law_doc("SOURCEA_FOUNDER_MACHINE_TERMINOLOGY_DICTIONARY_LOCKED_v1.md")
FOUNDER_DIRECTION_TERMS = law_doc("SOURCEA_FOUNDER_DIRECTION_TERMINOLOGY_LOCKED_v1.md")
SUPER_FAST_HUB = law_doc("SOURCEA_SUPER_FAST_HUB_LOCKED_v1.md")
AGENTIC_LAYER_STACK = law_doc("SOURCEA_AGENTIC_LAYER_STACK_LOCKED_v2.md")
LIVE_ONGOING_PROMPTS = law_doc("SOURCEA_LIVE_ONGOING_PROMPTS_LOCKED_v1.md")
PHASE_STRICT_RUN_INBOX = law_doc("SOURCEA_PHASE_STRICT_RUN_INBOX_LOCKED_v1.md")
OPENROUTER_ACTIVATION_QUEUE = law_doc("SOURCEA_OPENROUTER_ACTIVATION_QUEUE_LOCKED_v1.md")
INCIDENT_FIX_OWNERSHIP = law_doc("SOURCEA_INCIDENT_FIX_OWNERSHIP_GOVERNANCE_HARDENING_LOCKED_v1.md")
RESULT_DRIVEN_DISCUSSION = law_doc("SOURCEA_RESULT_DRIVEN_DISCUSSION_POLICY_LOCKED_v1.md")
CURSOR_RULES_MAP = law_doc("SOURCEA_CURSOR_RULES_AND_SKILLS_MAP_LOCKED_v2.md")
CURSOR_FIND_BUGS_AUTOMATION = law_doc("CURSOR_FIND_BUGS_AUTOMATION_LOCKED_v1.md")
AUTHORITY_REGISTRY_GOV = law_doc("SOURCEA_AUTHORITY_REGISTRY_GOV_UNIFY_BATCH_2026-06-11_LOCKED_v1.md")
S10_ETERNAL_AUDIT = law_doc("SOURCEA_S10_ETERNAL_SELF_HEAL_AUDIT_LOCKED_v1.md")
REF_ARCH_CONSTELLATION = law_doc("SOURCEA_REFERENCE_ARCHITECTURE_CONSTELLATION_LOCKED_v1.md")
FIVE_STEP_BLUEPRINT = law_doc("SOURCEA_FIVE_STEP_AUTONOMOUS_PROGRESS_BLUEPRINT_LOCKED_v1.md")
FORK_MACHINE = law_doc("SOURCEA_COMPLEX_SITUATION_FORK_MACHINE_LOCKED_v1.md")
INTEGRITY_PLAYBOOK = law_doc("SOURCEA_SYSTEM_INTEGRITY_100_STEP_PLAYBOOK_LOCKED_v1.md")
INTEGRITY_SESSION_LOG = law_doc("SOURCEA_SYSTEM_INTEGRITY_SESSION_LOG_v1.md")

# Batch 5b — WORLD_* WTM docs (canonical under brain-os/wtm/)
def wtm_doc(name: str) -> Path:
    """Resolve a LOCKED WTM filename under brain-os/wtm/."""
    return WTM / name


WTM_MAP = wtm_doc("WORLD_TARGET_MODEL_MAP_LOCKED_v5.md")
WTM_AUTHORITY = wtm_doc("WORLD_TARGET_MODEL_AUTHORITY_LAW_LOCKED_v1.md")
WTM_ROADMAP_LAW = wtm_doc("WORLD_TARGET_MODEL_ROADMAP_LAW_LOCKED_v2.md")
WTM_STEP_ID_MIGRATION = wtm_doc("WORLD_TARGET_MODEL_STEP_ID_MIGRATION_LOCKED_v1.md")
WTM_ARCHITECTURE_DIAGRAM = wtm_doc("WORLD_TARGET_MODEL_ARCHITECTURE_DIAGRAM_LOCKED_v1.md")
WTM_UI_RESEARCH = wtm_doc("WORLD_TARGET_MODEL_UI_RESEARCH_LOCKED_v1.md")
WTM_UI_INCIDENT = wtm_doc("WORLD_TARGET_MODEL_UI_INCIDENT_REPORT_LOCKED_v1.md")
WTM_PHASE_NAMING_INCIDENT = wtm_doc("WORLD_TARGET_MODEL_PHASE_NAMING_INCIDENT_REPORT_LOCKED_v1.md")
WTM_BLUEPRINT_V1 = wtm_doc("WORLD_TARGET_MODEL_FULL_BLUEPRINT_FOR_REVIEW_v1.md")
WTM_BLUEPRINT_V2 = wtm_doc("WORLD_TARGET_MODEL_FULL_BLUEPRINT_FOR_REVIEW_v2.md")

# Batch 5c — FOUNDER_* enforcement docs (canonical under brain-os/law/enforcement/)
def enforcement_doc(name: str) -> Path:
    """Resolve a LOCKED enforcement filename under brain-os/law/enforcement/."""
    return ENFORCEMENT / name


def incident_doc(name: str) -> Path:
    """Resolve an incident report filename under brain-os/incidents/."""
    return INCIDENTS / name


# Batch 5e — hot SINA_* paths (canonical under brain-os/law/ or incidents/)
SINA_AUTOMATION_SPINE = law_doc("SINA_AUTOMATION_SPINE_AND_N8N_LOCKED_v1.md")
SINA_APPS_GUIDE = law_doc("SINA_APPS_GUIDE_FOR_SINA_v1.md")
SINA_SEMI_SEPARATE = law_doc("SINA_SEMI_SEPARATE_AGENT_NOTICE_LOCKED_v1.md")
SINA_HUB_ESSENTIALS = law_doc("SINA_HUB_ESSENTIALS_LOCKED_v1.md")
SINA_PERSONAL_DB = law_doc("SINA_PERSONAL_DATABASE_LAYER_A_LOCKED_v1.md")
SINA_DAILY_BOWL = law_doc("SINA_DAILY_BOWL_LOCKED_v1.md")
SINA_STATIC_PROMPT_INCIDENT_024 = incident_doc(
    "SINA_STATIC_PROMPT_FEED_STALE_LIST_INCIDENT_024_REPORT_LOCKED_v1.md"
)

# Batch 5f — hot OTHER paths
SYSTEM = ROOT / "brain-os" / "system"
README_SOURCE_A = ENTRY / "README_SOURCE_A.md"
WIRE_LANE_PROGRESS = law_doc("WIRE_LANE_PROGRESS.md")
GOVERNANCE_DRIFT_ENGINE = law_doc("GOVERNANCE_DRIFT_ENGINE_LOCKED_v1.md")
SECRETS_VAULT = SYSTEM / "SECRETS_VAULT.md"
PORT_REGISTRY = SYSTEM / "PORT_REGISTRY.md"
PORT_NOTICE_BOARD = SYSTEM / "PORT_NOTICE_BOARD.md"
SINAAI_AUTO_PASTE_INCIDENT = incident_doc("SINAAI_AUTO_PASTE_INCIDENT_REPORT_LOCKED_v1.md")
CHATGPT_EXTERNAL_CRITIC_LAW = law_doc("CHATGPT_EXTERNAL_CRITIC_LAW_LOCKED_v1.md")
DISPATCH_POLICY = law_doc("DISPATCH_POLICY_LOCKED_v1.md")

REL_SYSTEM_PREFIX = "brain-os/system/"
REL_README_SOURCE_A = "brain-os/law/entry/README_SOURCE_A.md"
REL_WIRE_LANE_PROGRESS = "brain-os/law/WIRE_LANE_PROGRESS.md"
REL_GOVERNANCE_DRIFT_ENGINE = "brain-os/law/GOVERNANCE_DRIFT_ENGINE_LOCKED_v1.md"
REL_SECRETS_VAULT = "brain-os/system/SECRETS_VAULT.md"
REL_LAW_SINA_PREFIX = "brain-os/law/"


FOUNDER_AGENT_USE_GUIDE = enforcement_doc("FOUNDER_AGENT_USE_GUIDE_LOCKED_v1.md")
FOUNDER_FIRST_ASSISTANT_TRACKING = enforcement_doc("FOUNDER_FIRST_ASSISTANT_TRACKING_LAW_LOCKED_v1.md")
FOUNDER_SAVE_AND_LOCK = enforcement_doc("FOUNDER_SAVE_AND_LOCK_IMMEDIATE_APP_LAW_LOCKED_v1.md")
FOUNDER_NO_CREDIT_CARD = enforcement_doc("FOUNDER_NO_CREDIT_CARD_INFRA_LOCKED_v1.md")
FOUNDER_DAILY_PROMPT_PACK = enforcement_doc("FOUNDER_DAILY_PROMPT_PACK_LOCKED_v1.md")
FOUNDER_BRAIN_MAINTAINER_EXTRACTION = enforcement_doc("FOUNDER_BRAIN_MAINTAINER_STRATEGIC_EXTRACTION_100M_v2.md")

REL_ENFORCEMENT_PREFIX = "brain-os/law/enforcement/"
REL_FOUNDER_AGENT_USE_GUIDE = "brain-os/law/enforcement/FOUNDER_AGENT_USE_GUIDE_LOCKED_v1.md"
REL_FOUNDER_FIRST_ASSISTANT = "brain-os/law/enforcement/FOUNDER_FIRST_ASSISTANT_TRACKING_LAW_LOCKED_v1.md"
REL_FOUNDER_SAVE_AND_LOCK = "brain-os/law/enforcement/FOUNDER_SAVE_AND_LOCK_IMMEDIATE_APP_LAW_LOCKED_v1.md"
REL_FOUNDER_NO_CREDIT_CARD = "brain-os/law/enforcement/FOUNDER_NO_CREDIT_CARD_INFRA_LOCKED_v1.md"
REL_FOUNDER_DAILY_PROMPT_PACK = "brain-os/law/enforcement/FOUNDER_DAILY_PROMPT_PACK_LOCKED_v1.md"
REL_FOUNDER_BRAIN_MAINTAINER = "brain-os/law/enforcement/FOUNDER_BRAIN_MAINTAINER_STRATEGIC_EXTRACTION_100M_v2.md"
REL_CURSOR_FIND_BUGS = "brain-os/law/CURSOR_FIND_BUGS_AUTOMATION_LOCKED_v1.md"

REL_LAW_PREFIX = "brain-os/law/"
REL_WTM_PREFIX = "brain-os/wtm/"
REL_WTM_MAP = "brain-os/wtm/WORLD_TARGET_MODEL_MAP_LOCKED_v5.md"
REL_WTM_AUTHORITY = "brain-os/wtm/WORLD_TARGET_MODEL_AUTHORITY_LAW_LOCKED_v1.md"
REL_WTM_ROADMAP_LAW = "brain-os/wtm/WORLD_TARGET_MODEL_ROADMAP_LAW_LOCKED_v2.md"
REL_WTM_STEP_ID_MIGRATION = "brain-os/wtm/WORLD_TARGET_MODEL_STEP_ID_MIGRATION_LOCKED_v1.md"
REL_WTM_UI_INCIDENT = "brain-os/wtm/WORLD_TARGET_MODEL_UI_INCIDENT_REPORT_LOCKED_v1.md"
REL_WTM_PHASE_NAMING_INCIDENT = "brain-os/wtm/WORLD_TARGET_MODEL_PHASE_NAMING_INCIDENT_REPORT_LOCKED_v1.md"
REL_COMMERCIAL_SSOT = "brain-os/law/SOURCEA_UNIFIED_PORTFOLIO_COMMERCIAL_SSOT_LOCKED_v3.1.md"
REL_GOVERNANCE_ENTRY = "brain-os/law/entry/SINA_GOVERNANCE_ENTRY_LOCKED_v1.md"
REL_AUTHORITY_INDEX = "brain-os/system/SINA_AUTHORITY_INDEX_MAP_LOCKED_v1.md"
REL_SINA_OS_SSOT = "brain-os/law/SINA_OS_SSOT_LOCKED.md"
REL_NO_FAKE_PROGRESS = "brain-os/law/SOURCEA_NO_FAKE_PROGRESS_ENTERPRISE_SHIP_LOCKED_v1.md"
