#!/usr/bin/env bash
# Switch Mac Vercel CLI from trial (noetfield-systems) to main (the-777-foundation).
#
# Law: data/vercel-portfolio-map-v1.json · docs/PORTFOLIO_VERCEL_CONSOLIDATION_LOCKED_v1.md
# Receipt: ~/.sina/vercel-cli-main-switch-receipt-v1.json
#
# Usage:
#   bash scripts/switch_vercel_cli_main_v1.sh              # open Terminal OAuth (recommended)
#   bash scripts/switch_vercel_cli_main_v1.sh --token '…'  # save main PAT + wire env
#   bash scripts/switch_vercel_cli_main_v1.sh --check      # verify only
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SINA="${HOME}/.sina"
TOKEN_FILE="${SINA}/sourcea-vercel-token-v1.json"
ENV_FILE="${SINA}/vercel-main-cli-v1.env"
RECEIPT="${SINA}/vercel-cli-main-switch-receipt-v1.json"
MAIN_EMAIL="kazemnezhadsina144@gmail.com"
MAIN_SCOPE="the-777-foundation"
TRIAL_SCOPE="noetfield-systems"
TRIAL_USER_PATTERN="noetfield"

vercel_cmd() {
  if command -v vercel >/dev/null 2>&1; then
    vercel "$@"
  else
    npx --yes vercel@latest "$@"
  fi
}

write_env() {
  mkdir -p "${SINA}"
  cat >"${ENV_FILE}" <<EOF
# SourceA main Vercel CLI — auto-generated by switch_vercel_cli_main_v1.sh
# Source: ${MAIN_EMAIL} · team ${MAIN_SCOPE}
export SOURCEA_VERCEL_SCOPE="${MAIN_SCOPE}"
export SOURCEA_VERCEL_PROJECT="source-a"
export WITNESSBC_VERCEL_SCOPE="${MAIN_SCOPE}"
export WITNESSBC_VERCEL_PROJECT="witnessbc-governance-main"
export VERCEL_ORG_ID=""
export VERCEL_TEAM="${MAIN_SCOPE}"
EOF
  chmod 600 "${ENV_FILE}"
}

save_token() {
  local tok="$1"
  python3 "${ROOT}/scripts/sourcea_vercel_token_setup_v1.py" \
    --token "${tok}" \
    --project source-a \
    --name "SourceA main Vercel" \
    --json >/dev/null
  python3 - <<'PY'
import json, os
from pathlib import Path
p = Path.home() / ".sina" / "sourcea-vercel-token-v1.json"
row = json.loads(p.read_text())
row["scope"] = "the-777-foundation"
row["lane"] = "main_portfolio"
p.write_text(json.dumps(row, indent=2) + "\n")
os.chmod(p, 0o600)
PY
  # Token auth — export for child shells (do not echo token)
  grep -v '^#' "${ENV_FILE}" >/dev/null 2>&1 || write_env
  if ! grep -q 'VERCEL_TOKEN=' "${ENV_FILE}" 2>/dev/null; then
    echo "export VERCEL_TOKEN=\"${tok}\"" >>"${ENV_FILE}"
    chmod 600 "${ENV_FILE}"
  fi
}

whoami_line() {
  vercel_cmd whoami 2>/dev/null | tail -1 || true
}

teams_has_main() {
  vercel_cmd teams ls 2>/dev/null | grep -q "${MAIN_SCOPE}" || \
    vercel_cmd teams ls 2>/dev/null | grep -qi "777"
}

check_status() {
  local who teams_ok token_ok=0
  who="$(whoami_line)"
  if [[ -f "${TOKEN_FILE}" ]]; then
    token_ok=1
  fi
  if teams_has_main; then
    teams_ok=1
  else
    teams_ok=0
  fi
  python3 - <<PY
import json, datetime
from pathlib import Path
row = {
  "schema": "vercel-cli-main-switch-v1",
  "at": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
  "whoami": "${who}",
  "main_scope": "${MAIN_SCOPE}",
  "teams_has_main": bool(${teams_ok}),
  "token_file": bool(${token_ok}),
  "env_file": str(Path("${ENV_FILE}")),
  "ok": bool(${teams_ok}) or bool(${token_ok}),
}
Path("${RECEIPT}").write_text(json.dumps(row, indent=2) + "\\n")
print(json.dumps(row, indent=2))
PY
}

open_terminal_login() {
  local script="${SINA}/vercel-main-login-terminal-v1.sh"
  cat >"${script}" <<'EOS'
#!/usr/bin/env bash
set -euo pipefail
echo "=== Vercel CLI → MAIN account ==="
echo "Email: kazemnezhadsina144@gmail.com"
echo "Team:  the-777-foundation"
echo ""
if command -v vercel >/dev/null 2>&1; then VC=vercel; else VC="npx --yes vercel@latest"; fi
echo "Logging out trial session (if any)…"
$VC logout 2>/dev/null || true
echo ""
echo "Opening browser — sign in as kazemnezhadsina144@gmail.com"
$VC login
echo ""
echo "Teams:"
$VC teams ls
echo ""
echo "Whoami:"
$VC whoami
echo ""
if $VC teams ls 2>/dev/null | grep -q "the-777-foundation"; then
  echo "PASS: main team visible — CLI is on MAIN"
else
  echo "FAIL: the-777-foundation not in teams list — wrong Gmail?"
  exit 1
fi
EOS
  chmod +x "${script}"
  open -a Terminal "${script}"
}

MODE="${1:-}"
TOKEN=""
case "${MODE}" in
  --token)
    TOKEN="${2:-}"
    if [[ -z "${TOKEN}" ]]; then
      echo "Usage: $0 --token '<main-account-pat>'" >&2
      exit 1
    fi
    write_env
    save_token "${TOKEN}"
    export VERCEL_TOKEN="${TOKEN}"
    export SOURCEA_VERCEL_SCOPE="${MAIN_SCOPE}"
    if teams_has_main || vercel_cmd whoami >/dev/null 2>&1; then
      echo "PASS: main token saved · scope=${MAIN_SCOPE}"
    else
      echo "PASS: token saved (whoami via token — OAuth optional)"
    fi
    check_status
    ;;
  --check)
    check_status
    ;;
  --terminal|"")
    write_env
    echo "Opening Terminal.app for real Vercel OAuth (Cursor agent cannot save CLI session)."
    echo "Sign in as: ${MAIN_EMAIL}"
    open_terminal_login
    echo "Env wired: ${ENV_FILE}"
    echo "After Terminal shows PASS, run: bash scripts/switch_vercel_cli_main_v1.sh --check"
    ;;
  *)
    echo "Usage: $0 [--terminal | --token '<pat>' | --check]" >&2
    exit 1
    ;;
esac
